"use client";
/* eslint-disable @next/next/no-img-element */

import { useState } from "react";
import { SubmitButton } from "@/components/submit-button";
import type { StoreProductRow } from "@/lib/database.types";
import { STORE_FILTH_AUDIENCES, STORE_FULFILLMENT_TYPES, STORE_PRODUCT_STATUSES, STORE_PRODUCT_TYPES, storeLabel } from "@/lib/store";

function AdminSwitch({ name, label, checked, onChange }: { name: string; label: string; checked: boolean; onChange: (checked: boolean) => void }) {
  return <label className="admin-switch-row"><span>{label}</span><input name={name} type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /><span className="admin-switch" aria-hidden="true"><span /></span><strong>{checked ? "On" : "Off"}</strong></label>;
}

export function AdminStoreProductForm({ action, product, imageUrl }: { action: (formData: FormData) => void | Promise<void>; product?: StoreProductRow; imageUrl?: string | null }) {
  const [moneyEnabled, setMoneyEnabled] = useState(product?.money_enabled ?? true);
  const [filthEnabled, setFilthEnabled] = useState(product?.filth_enabled ?? false);
  const [inventoryUnlimited, setInventoryUnlimited] = useState(product?.inventory_unlimited ?? true);
  const [fulfillmentType, setFulfillmentType] = useState(product?.fulfillment_type ?? "manual");
  return <form action={action} className="form-grid store-product-form">
    <fieldset className="full-span store-editor-section"><legend>Product</legend><div className="store-product-fields"><div className="store-product-identity"><label>Name<input name="name" defaultValue={product?.name} required maxLength={200} /></label><label>Slug<input name="slug" defaultValue={product?.slug} required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" /></label><label className="full-span">Short description<input name="short_description" defaultValue={product?.short_description} required maxLength={300} /></label><label className="full-span">Description<textarea name="description" defaultValue={product?.description} required rows={7} maxLength={10000} /></label><label>Product type<select name="product_type" defaultValue={product?.product_type ?? "membership"}>{STORE_PRODUCT_TYPES.map((type) => <option key={type} value={type}>{storeLabel(type)}</option>)}</select></label></div><div className="store-image-editor"><span className="admin-field-label">Product image</span>{imageUrl ? <img className="store-product-image-preview" src={imageUrl} alt="Current product" /> : <div className="store-image-empty">No image</div>}<label className="store-upload-button">{imageUrl ? "Replace" : "Upload image"}<input name="product_image" type="file" accept="image/png,image/jpeg,image/webp" /></label>{product?.image_path ? <label className="store-remove-image"><input name="remove_image" type="checkbox" /> Remove</label> : null}</div></div></fieldset>
    <fieldset className="full-span store-editor-section"><legend>Purchase options</legend><div className="store-acquisition-grid"><section className={`store-acquisition-card${moneyEnabled ? " is-enabled" : ""}`}><AdminSwitch name="money_enabled" label="Money purchases" checked={moneyEnabled} onChange={setMoneyEnabled} />{moneyEnabled ? <div className="store-card-fields"><label>Price amount<input name="price_amount" type="number" min="0" max="9999999999.99" step="0.01" defaultValue={product?.price_amount ?? 0} required /></label><label>Currency<input name="currency" defaultValue={product?.currency ?? "USD"} pattern="[A-Z]{3}" maxLength={3} required /></label></div> : <p className="admin-muted">Hidden from monetary checkout.</p>}</section><section className={`store-acquisition-card${filthEnabled ? " is-enabled" : ""}`}><AdminSwitch name="filth_enabled" label="Filth redemption" checked={filthEnabled} onChange={setFilthEnabled} />{filthEnabled ? <div className="store-card-fields"><label>Filth price<input name="filth_price" type="number" min="1" step="1" defaultValue={product?.filth_price ?? ""} required /></label><label>Redeemable by<select name="filth_audience" defaultValue={product?.filth_audience ?? "inner_sanctum"}>{STORE_FILTH_AUDIENCES.map((audience) => <option key={audience} value={audience}>{audience === "inner_sanctum" ? "Inner Sanctum members" : "Any authenticated member"}</option>)}</select></label></div> : <p className="admin-muted">No Filth acquisition configured.</p>}</section></div></fieldset>
    <fieldset className="full-span store-editor-section"><legend>Availability</legend><div className="store-choice-row"><span className="admin-field-label">Inventory</span><label className={`store-choice${inventoryUnlimited ? " is-selected" : ""}`}><input name="inventory_unlimited" type="radio" checked={inventoryUnlimited} onChange={() => setInventoryUnlimited(true)} />Unlimited</label><label className={`store-choice${!inventoryUnlimited ? " is-selected" : ""}`}><input name="inventory_unlimited_choice" type="radio" checked={!inventoryUnlimited} onChange={() => setInventoryUnlimited(false)} />Limited</label></div>{!inventoryUnlimited ? <div className="store-availability-fields"><label>Quantity available<input name="inventory_quantity" type="number" min="0" step="1" defaultValue={product?.inventory_quantity ?? ""} required /></label><label className="admin-check-row"><input name="show_remaining_quantity" type="checkbox" defaultChecked={product?.show_remaining_quantity ?? false} /> Show remaining quantity</label></div> : <input name="inventory_unlimited" type="hidden" value="on" />}</fieldset>
    <fieldset className="full-span store-editor-section store-editor-compact"><legend>Fulfillment</legend><div className="form-grid"><label>Fulfillment type<select name="fulfillment_type" value={fulfillmentType} onChange={(event) => setFulfillmentType(event.target.value as typeof fulfillmentType)}>{STORE_FULFILLMENT_TYPES.map((type) => <option key={type} value={type}>{storeLabel(type)}</option>)}</select></label>{fulfillmentType === "manual" ? <label>Fulfillment reference<input name="fulfillment_reference" defaultValue={product?.fulfillment_reference ?? ""} maxLength={200} /></label> : <input name="fulfillment_reference" type="hidden" value="" />}</div></fieldset>
    <fieldset className="full-span store-editor-section store-editor-compact"><legend>Publishing</legend><div className="form-grid"><label>Status<select name="status" defaultValue={product?.status ?? "draft"}>{STORE_PRODUCT_STATUSES.map((status) => <option key={status} value={status}>{storeLabel(status)}</option>)}</select></label><label>Sort order<input name="sort_order" type="number" min="-10000" max="10000" defaultValue={product?.sort_order ?? 0} required /></label></div></fieldset>
    <div className="full-span store-editor-actions"><SubmitButton>{product ? "Save product" : "Create product"}</SubmitButton></div>
  </form>;
}
