import type { BookingSource, BookingStatus, EnquiryStatus, HoldStatus, PaymentStatus, QuoteStatus, RetreatFormat } from "./domain";

export type TeaserStatus = "draft" | "published";
export type TeaserVisibility = "private" | "public";
export type TeaserRow = { destination_type: "store" | "promo"; promo_destination: "contribute" | null; id: string; internal_name: string; eyebrow: string | null; title: string; body: string; graffiti_lines: string[]; image_1_path: string | null; image_2_path: string | null; image_3_path: string | null; store_product_id: string | null; slug: string; status: TeaserStatus; visibility: TeaserVisibility; created_by: string | null; created_at: string; updated_at: string; published_at: string | null };
export type PublishedTeaser = Pick<TeaserRow, "id" | "slug" | "eyebrow" | "title" | "body" | "graffiti_lines" | "image_1_path" | "image_2_path" | "image_3_path" | "visibility" | "destination_type" | "promo_destination" | "store_product_id" | "published_at"> & { store_product_active: boolean };
export type TeaserInsert = Pick<TeaserRow, "internal_name" | "title" | "body"> & Partial<Pick<TeaserRow, "destination_type" | "promo_destination" | "eyebrow" | "graffiti_lines" | "image_1_path" | "image_2_path" | "image_3_path" | "store_product_id">>;
export type TeaserUpdate = Partial<TeaserInsert & Pick<TeaserRow, "status" | "visibility">>;

export type ContributionCategory = "design" | "development" | "creative" | "marketing" | "idea" | "experience_event" | "other";
export type ContributionStatus = "submitted" | "reviewing" | "accepted" | "declined";
export type ContributionSubmissionRow = { id: string; user_id: string; category: ContributionCategory; title: string; description: string; work_url: string | null; additional_notes: string | null; status: ContributionStatus; submitted_at: string; reviewed_by: string | null; reviewed_at: string | null; filth_awarded: number; paid_opportunity: boolean; admin_note: string | null };
export type MyContribution = Omit<ContributionSubmissionRow, "user_id" | "reviewed_by" | "admin_note">;
export type ContributionProgress = { filth_total: number; accepted_contributions: number; filth_from_contributions: number; current_level_number: number | null; current_level_title: string | null; current_level_threshold: number | null; next_level_threshold: number | null; earned_milestones: Json };
export type AffiliateImpact = { successful_referrals: number; filth_from_referrals: number; recent_activity: Json };
export type AffiliateEarnings = { pending_total: number; available_total: number; commission_history: Json };

export type AffiliateCommissionRuleType = "percentage" | "fixed";
export type AffiliateCommissionSettingsRow = { id: boolean; default_commission_type: AffiliateCommissionRuleType; default_commission_value: number; commission_hold_days: number; updated_at: string };
export type AffiliateCommissionRow = { id: string; conversion_id: string; affiliate_account_id: string; referrer_user_id: string; gross_amount: number; commissionable_amount: number; rule_type: AffiliateCommissionRuleType; rule_value: number; commission_amount: number; status: "pending" | "available"; created_at: string; available_at: string; matured_at: string | null };
export type AffiliateAccountStatus = "active" | "suspended" | "closed";
export type AffiliateAccountRow = {
  id: string; user_id: string; status: AffiliateAccountStatus;
  created_at: string; updated_at: string; activated_at: string;
  suspended_at: string | null; closed_at: string | null;
  accepted_terms_version: string | null; terms_accepted_at: string | null;
};
export type AffiliateState = {
  has_account: boolean; affiliate_status: AffiliateAccountStatus | null;
  current_terms_version: string; accepted_terms_version: string | null;
  terms_accepted_at: string | null; has_accepted_current_terms: boolean;
};
export type InnerSanctumMembershipStatus = "active" | "suspended" | "cancelled";
export type InnerSanctumMembershipType = "lifetime";
export type InnerSanctumMembershipSource = "admin" | "store" | "promotion" | "migration";
export type InnerSanctumPostType = "message" | "feature" | "drop" | "task" | "benefit";
export type InnerSanctumPostStatus = "draft" | "published" | "archived";
export type InnerSanctumCollectibleStatus = "draft" | "active" | "archived";
export type InnerSanctumCollectibleSource = "admin" | "experience" | "task" | "invitation" | "system";
export type InnerSanctumBenefitType = "invitation" | "gift" | "experience" | "event" | "retreat" | "personal";
export type InnerSanctumBenefitStatus = "draft" | "available" | "withdrawn" | "completed" | "expired";
export type InnerSanctumBenefitResponse = "accepted" | "declined";
export type InnerSanctumTaskStatus = "draft" | "published" | "archived";
export type InnerSanctumReferralStatus = "active" | "disabled";
export type InnerSanctumReferralConversionSource = "payfast" | "admin_test" | "verified_payment";
export type StoreProductType = "membership" | "digital" | "experience" | "session" | "physical";
export type StoreProductStatus = "draft" | "active" | "archived";
export type StoreFulfillmentType = "inner_sanctum_membership" | "manual";
export type StoreOrderStatus = "pending" | "paid" | "cancelled" | "failed";
export type StoreFulfillmentAuthorizationSource = "admin" | "payfast";
export type StoreClaimStatus = "available" | "claimed" | "revoked";

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
type ProductRow = { id: string; slug: string; name: string; positioning: string; allowed_formats: RetreatFormat[]; is_published: boolean; sort_order: number; created_at: string; updated_at: string };
type AvailabilityRow = { id: string; retreat_product_id: string | null; retreat_format: RetreatFormat | null; start_date: string; end_date: string; state: "available" | "blocked"; capacity: number | null; created_at: string; updated_at: string };
type EventRow = { id: string; title: string; slug: string; retreat_product_id: string; retreat_format: RetreatFormat; start_date: string; end_date: string; capacity: number; available_places: number; status: "draft" | "published" | "full" | "cancelled" | "completed"; description: string | null; price_usd_per_person: number; invitation_only: boolean; interest_enabled: boolean; created_at: string; updated_at: string };
type PricingRow = { id: string; retreat_product_id: string; retreat_format: RetreatFormat; price_usd_per_person_per_night: number; created_at: string; updated_at: string };
type EnquiryRow = { id: string; enquiry_type: "stay" | "general"; full_name: string; email: string; phone: string; country: string; retreat_product_id: string | null; retreat_type_name: string | null; retreat_format: RetreatFormat | null; guest_count: number | null; requested_start_date: string | null; requested_end_date: string | null; alternative_date: string | null; retreat_event_id: string | null; message: string | null; referral_code: string | null; referral_source: string | null; estimated_total: number | null; estimated_currency: string | null; estimated_nights: number | null; status: EnquiryStatus; admin_notes: string | null; created_at: string; updated_at: string };
type QuoteRow = {
  id: string;
  reference: string;
  enquiry_id: string;
  retreat_product_id: string;
  retreat_type_name: string;
  retreat_format: RetreatFormat;
  start_date: string;
  end_date: string | null;
  duration_days: number | null;
  guest_count: number;
  total_price: number;
  rate_usd_per_person_per_night: number | null;
  deposit_required: number;
  currency: string;
  expiry_date: string | null;
  notes: string | null;
  payment_instructions: string | null;
  payment_token_hash: string | null;
  status: QuoteStatus;
  payment_status: PaymentStatus;
  payment_received_at: string | null;
  eth_amount: number | null;
  eth_converted_at: string | null;
  eth_price_usd: number | null;
  payment_submitted_at: string | null;
  payment_verified_at: string | null;
  payment_verified_by: string | null;
  payment_tx_hash: string | null;
  public_slug: string | null;
  created_at: string;
};

type QuoteInsert = Partial<QuoteRow> & {
  id?: string;
  created_at?: string;
  payment_received_at?: string | null;
  rate_usd_per_person_per_night?: number | null;
  public_slug?: string | null;
  payment_instructions?: string | null;
  payment_token_hash?: string | null;
  expiry_date?: string | null;
};
type InvoiceRow = {
  id: string;
  quote_id: string;
  enquiry_id: string;
  invoice_reference: string;
  amount_usd: number;
  eth_price_usd: number;
  amount_eth: number;
  wallet_address: string;
  public_slug: string;
  status: "awaiting_payment" | "payment_submitted" | "paid" | "cancelled";
  retry_allowed_at: string | null;
  retry_allowed_by: string | null;
  created_at: string;
  updated_at: string;
};
type PaymentSubmissionRow = {
  id: string;
  invoice_id: string;
  quote_id: string;
  enquiry_id: string;
  submitted_at: string;
  status: "submitted" | "verified" | "rejected";
  reviewed_at: string | null;
  reviewed_by: string | null;
  review_note: string | null;
  created_at: string;
};
type BookingRow = { id: string; enquiry_id: string | null; retreat_product_id: string; retreat_type_name: string; retreat_format: RetreatFormat; start_date: string; end_date: string | null; guest_count: number; retreat_event_id: string | null; retreat_event_interest_id: string | null; quote_id: string | null; invoice_id: string | null; payment_submission_id: string | null; booking_reference: string; public_slug: string; booking_status: BookingStatus; payment_status: PaymentStatus; booking_source: BookingSource; created_by: string | null; confirmed_at: string; confirmed_by: string | null; created_at: string; updated_at: string };
type HoldRow = { id: string; quote_id: string | null; enquiry_id: string; retreat_product_id: string; retreat_format: RetreatFormat; start_date: string; end_date: string | null; guest_count: number; retreat_event_id: string | null; status: HoldStatus; expires_at: string | null; created_at: string; updated_at: string };
type BookingPreparationRow = { id: string; booking_id: string; preferred_contact_method: "whatsapp" | "phone" | "email"; contact_detail: string; participant_names: string | null; arrival_method: string | null; arrival_notes: string | null; dietary_requirements: string | null; accessibility_requirements: string | null; cally_notes: string | null; created_at: string; updated_at: string };
export type InnerSanctumMembershipRow = {
  id: string;
  user_id: string;
  status: InnerSanctumMembershipStatus;
  membership_type: InnerSanctumMembershipType;
  source: InnerSanctumMembershipSource;
  source_reference: string | null;
  started_at: string;
  expires_at: string | null;
  suspended_at: string | null;
  cancelled_at: string | null;
  last_changed_by: string | null;
  created_at: string;
  updated_at: string;
};
export type InnerSanctumAdminMember = {
  user_id: string;
  email: string | null;
  created_at: string;
  membership_id: string | null;
  membership_status: InnerSanctumMembershipStatus | null;
  membership_type: InnerSanctumMembershipType | null;
  membership_source: InnerSanctumMembershipSource | null;
  source_reference: string | null;
  started_at: string | null;
  expires_at: string | null;
  suspended_at: string | null;
  cancelled_at: string | null;
  updated_at: string | null;
};
export type InnerSanctumPostRow = {
  id: string;
  type: InnerSanctumPostType;
  eyebrow: string | null;
  title: string;
  body: string;
  image_path: string | null;
  cta_label: string | null;
  cta_href: string | null;
  status: InnerSanctumPostStatus;
  published_at: string | null;
  expires_at: string | null;
  sort_order: number;
  created_by: string | null;
  created_at: string;
  updated_at: string;
};
export type InnerSanctumVisiblePost = Omit<InnerSanctumPostRow, "status" | "created_by" | "created_at" | "updated_at">;
export type InnerSanctumCollectibleRow = { id: string; slug: string; title: string; description: string; media_path: string | null; media_type: string | null; status: InnerSanctumCollectibleStatus; sort_order: number; created_at: string; updated_at: string };
export type InnerSanctumMemberCollectibleRow = { id: string; user_id: string; collectible_id: string; source: InnerSanctumCollectibleSource; source_reference: string | null; granted_at: string; granted_by: string | null };
export type InnerSanctumOwnedCollectible = Pick<InnerSanctumCollectibleRow, "id" | "slug" | "title" | "description" | "media_path" | "media_type" | "sort_order"> & { granted_at: string };
export type InnerSanctumBenefitRow = { id: string; user_id: string; type: InnerSanctumBenefitType; eyebrow: string | null; title: string; body: string; media_path: string | null; media_type: string | null; cta_label: string | null; cta_href: string | null; status: InnerSanctumBenefitStatus; response: InnerSanctumBenefitResponse | null; available_from: string | null; expires_at: string | null; retreat_event_id: string | null; created_by: string; created_at: string; updated_at: string; responded_at: string | null };
export type RetreatEventInterestRow = { id: string; retreat_event_id: string; user_id: string; message: string | null; status: "interested" | "selected" | "not_selected" | "withdrawn"; created_at: string; updated_at: string; reviewed_at: string | null; reviewed_by: string | null; admin_notes: string | null };
export type AdminRetreatEventInterest = RetreatEventInterestRow & { member_email: string | null; invitation_id: string | null; invitation_status: InnerSanctumBenefitStatus | null; invitation_response: InnerSanctumBenefitResponse | null };
export type InnerSanctumVisibleBenefit = Omit<InnerSanctumBenefitRow, "user_id" | "created_by" | "updated_at"> & { confirmed_booking_id: string | null; confirmed_booking_reference: string | null; confirmed_booking_public_slug: string | null; confirmed_booking_start_date: string | null; confirmed_booking_end_date: string | null };
export type InnerSanctumTaskRow = { id: string; slug: string; eyebrow: string | null; title: string; body: string; prompt: string; status: InnerSanctumTaskStatus; available_from: string | null; closes_at: string | null; sort_order: number; created_by: string | null; created_at: string; updated_at: string };
export type InnerSanctumTaskResponseRow = { id: string; task_id: string; user_id: string; response_text: string; submitted_at: string; acknowledged_at: string | null; acknowledged_by: string | null };
export type InnerSanctumMemberTask = Pick<InnerSanctumTaskRow, "id" | "slug" | "eyebrow" | "title" | "body" | "prompt" | "status" | "available_from" | "closes_at" | "sort_order"> & { response_text: string | null; submitted_at: string | null; acknowledged_at: string | null };
export type InnerSanctumReferralRow = { id: string; user_id: string; code: string; status: InnerSanctumReferralStatus; created_at: string; updated_at: string };
export type StoreOrderReferralRow = { id: string; order_id: string; referral_id: string; referrer_user_id: string; attributed_at: string; converted_at: string | null; conversion_id: string | null; created_at: string };
export type InnerSanctumFilthEventRow = { id: string; user_id: string; event_type: "referral" | "admin" | "task" | "experience" | "special" | "contribution"; points: number; source_reference: string; created_by: string | null; created_at: string };
export type InnerSanctumFilthMeter = { referral_code: string | null; filth_total: number; successful_referrals: number; current_level_number: number | null; current_level_title: string | null; current_level_threshold: number | null; next_level_threshold: number | null; earned_milestones: Array<{ title: string; threshold: number; earned_at: string }> };
export type InnerSanctumFilthLevelRow = { id: string; level_number: number; title: string; threshold: number; status: "active" | "inactive"; sort_order: number; created_at: string; updated_at: string };
export type InnerSanctumFilthMilestoneRow = { id: string; level_id: string | null; threshold: number; title: string; reward_type: "collectible" | "benefit" | "experience" | "retreat" | "manual"; reward_reference: string | null; status: "active" | "inactive"; sort_order: number; created_at: string; updated_at: string };
export type InnerSanctumMemberFilthMilestoneRow = { id: string; user_id: string; milestone_id: string; earned_at: string; fulfilled_at: string | null; fulfillment_reference: string | null };
export type StoreProductRow = { commission_type: AffiliateCommissionRuleType | null; commission_value: number | null; id: string; slug: string; name: string; short_description: string; description: string; product_type: StoreProductType; price_amount: number; currency: string; fulfillment_type: StoreFulfillmentType; fulfillment_reference: string | null; image_path: string | null; status: StoreProductStatus; sort_order: number; created_at: string; updated_at: string };
export type StorePaymentStatus = "pending" | "submitted" | "verified" | "rejected";
export type StorePaymentAudit = { payment_status: StorePaymentStatus; payment_method: string | null; payment_submitted_at: string | null; payment_reference: string | null; payment_verified_at: string | null; payment_verified_by: string | null; payment_reviewed_at: string | null; payment_reviewed_by: string | null; payment_verification_note: string | null; fulfilled_at: string | null };
export type StoreOrderRow = StorePaymentAudit & { id: string; order_reference: string; request_key: string; user_id: string | null; buyer_email: string; status: StoreOrderStatus; currency: string; subtotal_amount: number; total_amount: number; created_at: string; updated_at: string };
export type StoreOrderItemRow = { id: string; order_id: string; product_id: string; product_name: string; product_slug: string; product_type: StoreProductType; unit_price_amount: number; currency: string; quantity: number; line_total_amount: number; fulfillment_type: StoreFulfillmentType; fulfillment_reference: string | null; created_at: string };
export type StoreFulfillmentAuthorizationRow = { id: string; order_id: string; source: StoreFulfillmentAuthorizationSource; source_reference: string | null; authorized_by: string | null; authorized_at: string; created_at: string };
export type StoreClaimRow = { id: string; order_id: string; authorization_id: string; token_hash: string; status: StoreClaimStatus; claimed_by: string | null; claimed_at: string | null; revoked_at: string | null; expires_at: string | null; created_at: string };
export type StoreFulfillmentAdminRow = { authorization_id: string; authorization_source: StoreFulfillmentAuthorizationSource; source_reference: string | null; authorized_at: string; authorized_by: string | null; claim_id: string | null; claim_status: StoreClaimStatus | null; claim_created_at: string | null; claimed_by: string | null; claimed_email: string | null; claimed_at: string | null; revoked_at: string | null };

type Table<Row, Insert = Partial<Row>, Update = Partial<Insert>> = { Row: Row; Insert: Insert; Update: Update; Relationships: [] };
export type Database = {
  public: {
    Tables: {
      teasers: Table<TeaserRow, TeaserInsert, TeaserUpdate>;
      affiliate_commission_settings: Table<AffiliateCommissionSettingsRow, never, never>;
      affiliate_commissions: Table<AffiliateCommissionRow, never, never>;
      contribution_submissions: Table<ContributionSubmissionRow, never, never>;
      affiliate_accounts: Table<AffiliateAccountRow, never, never>;
      admin_users: Table<{ user_id: string; created_at: string }, { user_id: string; created_at?: string }>;
      retreat_products: Table<ProductRow, Omit<ProductRow, "id" | "created_at" | "updated_at"> & { id?: string; created_at?: string; updated_at?: string }>;
      retreat_availability: Table<AvailabilityRow, Omit<AvailabilityRow, "id" | "created_at" | "updated_at"> & { id?: string; created_at?: string; updated_at?: string }>;
      retreat_pricing: Table<PricingRow, Omit<PricingRow, "id" | "created_at" | "updated_at"> & { id?: string; created_at?: string; updated_at?: string }>;
      retreat_events: Table<EventRow, Omit<EventRow, "id" | "created_at" | "updated_at"> & { id?: string; created_at?: string; updated_at?: string }>;
      retreat_event_interests: Table<RetreatEventInterestRow, never, never>;
      retreat_enquiries: Table<EnquiryRow, Omit<EnquiryRow, "id" | "created_at" | "updated_at" | "status" | "admin_notes"> & { id?: string; created_at?: string; updated_at?: string; status?: EnquiryStatus; admin_notes?: string | null }>;
      retreat_quotes: Table<QuoteRow, QuoteInsert>;
      retreat_invoices: Table<InvoiceRow, Omit<InvoiceRow, "id" | "created_at" | "updated_at"> & { id?: string; created_at?: string; updated_at?: string }>;
      retreat_payment_submissions: Table<PaymentSubmissionRow, Omit<PaymentSubmissionRow, "id" | "created_at" | "submitted_at" | "status" | "reviewed_at" | "reviewed_by" | "review_note"> & { id?: string; created_at?: string; submitted_at?: string; status?: "submitted" | "verified" | "rejected"; reviewed_at?: string | null; reviewed_by?: string | null; review_note?: string | null }>;
      retreat_bookings: Table<BookingRow, Omit<BookingRow, "id" | "created_at" | "updated_at"> & { id?: string; created_at?: string; updated_at?: string; booking_source?: BookingSource; created_by?: string | null; enquiry_id?: string | null; quote_id?: string | null }>;
      retreat_holds: Table<HoldRow, never>;
      retreat_booking_preparation: Table<BookingPreparationRow, never>;
      inner_sanctum_memberships: Table<
        InnerSanctumMembershipRow,
        never,
        never
      >;
      inner_sanctum_posts: Table<
        InnerSanctumPostRow,
        Omit<InnerSanctumPostRow, "id" | "created_at" | "updated_at"> & { id?: string; created_at?: string; updated_at?: string },
        Partial<Omit<InnerSanctumPostRow, "id" | "created_at" | "updated_at">>
      >;
      inner_sanctum_collectibles: Table<InnerSanctumCollectibleRow, Omit<InnerSanctumCollectibleRow, "id" | "created_at" | "updated_at"> & { id?: string }, Partial<Omit<InnerSanctumCollectibleRow, "id" | "created_at" | "updated_at">>>;
      inner_sanctum_member_collectibles: Table<InnerSanctumMemberCollectibleRow, never, never>;
      inner_sanctum_benefits: Table<InnerSanctumBenefitRow, Omit<InnerSanctumBenefitRow, "id" | "created_at" | "updated_at" | "responded_at" | "response" | "retreat_event_id"> & { id?: string; response?: InnerSanctumBenefitResponse | null; responded_at?: string | null; retreat_event_id?: string | null }, Partial<Omit<InnerSanctumBenefitRow, "id" | "created_at" | "updated_at">>>;
      inner_sanctum_tasks: Table<InnerSanctumTaskRow, Omit<InnerSanctumTaskRow, "id" | "created_at" | "updated_at"> & { id?: string }, Partial<Omit<InnerSanctumTaskRow, "id" | "created_at" | "updated_at">>>;
      inner_sanctum_task_responses: Table<InnerSanctumTaskResponseRow, never, never>;
      inner_sanctum_referrals: Table<InnerSanctumReferralRow, never, Partial<Pick<InnerSanctumReferralRow, "status">>>;
      store_order_referrals: Table<StoreOrderReferralRow, never, never>;
      inner_sanctum_referral_conversions: Table<{ id: string; referral_id: string; referrer_user_id: string; referred_user_id: string; order_id: string; order_reference: string; points_awarded: number; conversion_source: InnerSanctumReferralConversionSource; converted_at: string; created_at: string }, never, never>;
      inner_sanctum_filth_events: Table<InnerSanctumFilthEventRow, never, never>;
      inner_sanctum_filth_settings: Table<{ id: boolean; referral_points: number; updated_at: string }, never, never>;
      inner_sanctum_filth_levels: Table<InnerSanctumFilthLevelRow, Partial<InnerSanctumFilthLevelRow>, Partial<InnerSanctumFilthLevelRow>>;
      inner_sanctum_filth_milestones: Table<InnerSanctumFilthMilestoneRow, Partial<InnerSanctumFilthMilestoneRow>, Partial<InnerSanctumFilthMilestoneRow>>;
      inner_sanctum_member_filth_milestones: Table<InnerSanctumMemberFilthMilestoneRow, never, never>;
      store_products: Table<StoreProductRow, Omit<StoreProductRow, "id" | "created_at" | "updated_at" | "commission_type" | "commission_value"> & { commission_type?: AffiliateCommissionRuleType | null; commission_value?: number | null; id?: string; created_at?: string; updated_at?: string }>;
      store_orders: Table<StoreOrderRow, never, never>;
      store_order_items: Table<StoreOrderItemRow, never, never>;
      store_fulfillment_authorizations: Table<StoreFulfillmentAuthorizationRow, never, never>;
      store_claims: Table<StoreClaimRow, never, never>;
    };
    Views: Record<string, never>;
      Functions: {
        get_published_teaser_by_slug: { Args: { p_slug: string }; Returns: PublishedTeaser[] };
        submit_contribution: { Args: { p_category: ContributionCategory; p_title: string; p_description: string; p_work_url?: string | null; p_additional_notes?: string | null }; Returns: string };
        get_my_contributions: { Args: Record<string, never>; Returns: MyContribution[] };
        admin_get_contributions: { Args: { p_status?: ContributionStatus | null; p_id?: string | null }; Returns: Array<ContributionSubmissionRow & { email: string | null }> };
        admin_mark_contribution_reviewing: { Args: { p_contribution_id: string }; Returns: ContributionSubmissionRow };
        admin_accept_contribution: { Args: { p_contribution_id: string; p_filth_award: number; p_paid_opportunity: boolean; p_admin_note?: string | null }; Returns: ContributionSubmissionRow };
        admin_decline_contribution: { Args: { p_contribution_id: string; p_admin_note?: string | null }; Returns: ContributionSubmissionRow };
        get_my_contribution_progress: { Args: Record<string, never>; Returns: ContributionProgress[] };
        get_my_affiliate_impact: { Args: Record<string, never>; Returns: AffiliateImpact[] };
        get_my_affiliate_earnings: { Args: Record<string, never>; Returns: AffiliateEarnings[] };
        bind_my_store_order: { Args: { p_order_reference: string }; Returns: StoreOrderRow };
        get_my_store_checkout: { Args: { p_order_reference: string }; Returns: StoreOrderRow };
        submit_my_store_payment: { Args: { p_order_reference: string; p_payment_method: string; p_payment_reference?: string | null }; Returns: StoreOrderRow };
        admin_verify_store_payment: { Args: { p_order_id: string; p_note?: string | null }; Returns: StoreOrderRow };
        admin_reject_store_payment: { Args: { p_order_id: string; p_note?: string | null }; Returns: StoreOrderRow };
        accept_current_affiliate_terms: { Args: { p_terms_version: string; p_accept_terms: boolean }; Returns: AffiliateAccountRow };
        get_my_affiliate_state: { Args: Record<string, never>; Returns: AffiliateState[] };
        get_public_event_by_slug: { Args: { p_slug: string }; Returns: { id: string; slug: string; title: string; retreat_product_id: string; start_date: string; end_date: string; capacity: number; available_places: number; effective_places_remaining: number; description: string | null; invitation_only: boolean; interest_enabled: boolean }[] };
        has_inner_sanctum_access: { Args: Record<string, never>; Returns: boolean };
        get_my_inner_sanctum_access: { Args: Record<string, never>; Returns: Array<{ has_access: boolean; membership_status: InnerSanctumMembershipStatus; membership_type: InnerSanctumMembershipType; started_at: string; expires_at: string | null }> };
        get_inner_sanctum_posts: { Args: Record<string, never>; Returns: InnerSanctumVisiblePost[] };
        get_my_inner_sanctum_collection: { Args: Record<string, never>; Returns: InnerSanctumOwnedCollectible[] };
        admin_grant_inner_sanctum_collectible: { Args: { p_user_id: string; p_collectible_id: string; p_source_reference?: string | null }; Returns: InnerSanctumMemberCollectibleRow };
        get_my_inner_sanctum_benefits: { Args: Record<string, never>; Returns: InnerSanctumVisibleBenefit[] };
        respond_to_inner_sanctum_benefit: { Args: { p_benefit_id: string; p_response: InnerSanctumBenefitResponse }; Returns: InnerSanctumBenefitResponse };
        get_my_inner_sanctum_tasks: { Args: Record<string, never>; Returns: InnerSanctumMemberTask[] };
        get_my_inner_sanctum_task: { Args: { p_slug: string }; Returns: InnerSanctumMemberTask[] };
        submit_inner_sanctum_task_response: { Args: { p_task_id: string; p_response_text: string }; Returns: string };
        admin_acknowledge_inner_sanctum_task_response: { Args: { p_response_id: string }; Returns: string };
        is_valid_inner_sanctum_referral_code: { Args: { p_code: string }; Returns: boolean };
        get_or_create_my_referral_identity: { Args: Record<string, never>; Returns: InnerSanctumReferralRow };
        get_my_filth_meter: { Args: Record<string, never>; Returns: InnerSanctumFilthMeter[] };
        admin_record_test_referral_conversion: { Args: { p_order_id: string; p_referred_user_id: string }; Returns: string };
        admin_add_filth_points: { Args: { p_user_id: string; p_points: number; p_reason: string }; Returns: string };
        admin_list_inner_sanctum_members: { Args: Record<string, never>; Returns: InnerSanctumAdminMember[] };
        admin_transition_inner_sanctum_membership: { Args: { p_user_id: string; p_action: "grant" | "suspend" | "restore" | "cancel"; p_source?: InnerSanctumMembershipSource; p_source_reference?: string | null }; Returns: InnerSanctumMembershipRow };
        create_public_store_order: { Args: { p_product_id: string; p_buyer_email: string; p_request_key: string; p_referral_code?: string | null }; Returns: Array<{ order_reference: string; order_status: StoreOrderStatus; currency: string; total_amount: number }> };
        get_public_store_order: { Args: { p_order_reference: string }; Returns: Array<{ order_reference: string; order_status: StoreOrderStatus; currency: string; total_amount: number; created_at: string; product_name: string; product_slug: string; product_type: StoreProductType; quantity: number }> };
        admin_authorize_store_fulfillment: { Args: { p_order_id: string; p_token_hash: string; p_source_reference?: string | null }; Returns: Array<{ authorization_id: string; claim_id: string; claim_status: StoreClaimStatus }> };
        admin_reissue_store_claim: { Args: { p_order_id: string; p_token_hash: string }; Returns: Array<{ claim_id: string; claim_status: StoreClaimStatus }> };
        admin_revoke_store_claim: { Args: { p_order_id: string }; Returns: StoreClaimStatus };
        admin_get_store_fulfillment: { Args: { p_order_id: string }; Returns: StoreFulfillmentAdminRow[] };
        get_store_claim_state: { Args: { p_token: string }; Returns: Array<{ claim_state: "invalid" | "revoked" | "claimed" | "available"; product_name: string | null }> };
        redeem_store_claim: { Args: { p_token: string }; Returns: Array<{ redemption_state: "invalid" | "revoked" | "claimed" | "already_member" | "success"; order_reference: string | null }> };
        get_public_retreat_price: { Args: { p_product_id: string; p_format: RetreatFormat; p_guest_count: number }; Returns: { currency: "USD"; nights: 3; guest_count: number; total_usd: number }[] };
        get_private_arrival_availability: { Args: { p_product_id: string; p_format: RetreatFormat; p_guest_count: number; p_nights: number; p_month_start: string; p_month_end: string }; Returns: { arrival_date: string }[] };
        check_stay_availability: { Args: { p_product_id: string; p_format: RetreatFormat; p_arrival: string; p_nights: number; p_guest_count: number }; Returns: { available: boolean; state: string; arrival_date: string; nights: number; checkout_date: string; occupied_start: string; occupied_end: string }[] };
        get_arrival_availability: { Args: { p_product_id: string; p_format: RetreatFormat; p_nights: number; p_guest_count: number; p_range_start: string; p_range_end: string }; Returns: { available: boolean; state: string; arrival_date: string; nights: number; checkout_date: string; occupied_start: string; occupied_end: string }[] };
        get_admin_arrival_availability: { Args: { p_product_id: string; p_format: RetreatFormat; p_nights: number; p_guest_count: number; p_range_start: string; p_range_end: string }; Returns: { available: boolean; state: string; arrival_date: string; nights: number; checkout_date: string; occupied_start: string; occupied_end: string }[] };
        set_admin_enquiry_retreat_date: { Args: { p_enquiry_id: string; p_arrival: string }; Returns: { start_date: string; end_date: string; expires_at: string }[] };
        release_admin_enquiry_hold: { Args: { p_enquiry_id: string }; Returns: undefined };
        list_public_retreat_events: { Args: Record<string, never>; Returns: { id: string; slug: string; title: string; retreat_product_id: string; start_date: string; end_date: string; capacity: number; available_places: number; effective_places_remaining: number; description: string | null; invitation_only: boolean; interest_enabled: boolean }[] };
        express_interest_in_retreat_event: { Args: { p_event_id: string; p_message?: string | null }; Returns: Array<{ interest_id: string; interest_status: string }> };
        admin_list_retreat_event_interests: { Args: { p_event_id: string }; Returns: (AdminRetreatEventInterest & { confirmed_booking_id: string | null; confirmed_booking_reference: string | null; confirmed_booking_status: BookingStatus | null })[] };
        admin_set_retreat_event_interest_status: { Args: { p_interest_id: string; p_status: string; p_admin_notes?: string | null }; Returns: string };
        admin_create_retreat_event_invitation: { Args: { p_interest_id: string; p_personal_note?: string | null }; Returns: string };
        confirm_retreat_event_interest_booking: { Args: { p_interest_id: string }; Returns: string };
      confirm_retreat_booking: { Args: { target_quote_id: string }; Returns: string };
      create_manual_retreat_booking: { Args: { p_retreat_product_id: string; p_retreat_format: RetreatFormat; p_start_date: string; p_end_date: string | null; p_guest_count: number; p_booking_status: BookingStatus; p_payment_status: PaymentStatus; p_event_id: string | null }; Returns: string };
      create_quote_with_hold: { Args: { p_reference: string; p_enquiry_id: string; p_start_date: string; p_end_date: string | null; p_duration_days: number | null; p_total_price: number; p_deposit_required: number; p_currency: string; p_expiry_date: string; p_notes: string | null; p_payment_instructions: string; p_payment_token_hash: string }; Returns: string };
      expire_retreat_holds: { Args: Record<string, never>; Returns: number };
      create_retreat_event: { Args: { p_title:string; p_product_id:string; p_start_date:string; p_end_date:string; p_capacity:number; p_status:string; p_description:string|null; p_invitation_only?: boolean; p_interest_enabled?: boolean }; Returns:string };
      update_retreat_event: { Args: { p_event_id:string; p_title:string; p_start_date:string; p_end_date:string; p_capacity:number; p_status:string; p_description:string|null; p_invitation_only?: boolean; p_interest_enabled?: boolean }; Returns:undefined };
        get_retreat_quote_by_token: { Args: { raw_token: string }; Returns: Array<{ reference: string; retreat_type_name: string; retreat_format: RetreatFormat; start_date: string; end_date: string | null; guest_name: string; guest_count: number; total_price: number; deposit_required: number; currency: string; expiry_date: string; notes: string | null; payment_instructions: string; quote_status: QuoteStatus; payment_status: PaymentStatus; eth_amount: number | null; eth_converted_at: string | null; payment_submitted_at: string | null; payment_verified_at: string | null; payment_tx_hash: string | null; retreat_event_id: string | null; event_title: string | null }> };
        get_public_quote_by_slug: { Args: { p_public_slug: string }; Returns: Array<{ id: string; guest_name: string; retreat_type_name: string; retreat_format: RetreatFormat; guest_count: number; start_date: string; end_date: string | null; nights: number | null; total_price: number; rate_usd_per_person_per_night: number | null; currency: string; invoice_public_slug: string | null; created_at: string }> };
        get_public_invoice_by_slug: { Args: { p_public_slug: string }; Returns: Array<{ invoice_reference: string; guest_name: string; retreat_type_name: string; retreat_format: RetreatFormat; guest_count: number; start_date: string; end_date: string | null; amount_usd: number; amount_eth: number; eth_price_usd: number; wallet_address: string; status: "awaiting_payment" | "payment_submitted" | "paid" | "cancelled"; retry_allowed: boolean; payment_issue: boolean; created_at: string }> };
        submit_invoice_payment: { Args: { p_public_slug: string }; Returns: Array<{ submission_status: "payment_submitted"; submitted_at: string; hold_status: HoldStatus; hold_expires_at: string | null }> };
        verify_invoice_payment: { Args: { p_invoice_id: string; p_review_note: string | null }; Returns: Array<{ submission_status: "verified" | "rejected"; invoice_status: "paid" | "awaiting_payment" | "payment_submitted"; reviewed_at: string; reviewed_by: string; hold_status: HoldStatus; hold_expires_at: string | null; review_note: string | null }> };
        reject_invoice_payment: { Args: { p_invoice_id: string; p_review_note: string | null }; Returns: Array<{ submission_status: "verified" | "rejected"; invoice_status: "paid" | "awaiting_payment" | "payment_submitted"; reviewed_at: string; reviewed_by: string; hold_status: HoldStatus; hold_expires_at: string | null; review_note: string | null }> };
        allow_invoice_payment_retry: { Args: { p_invoice_id: string }; Returns: Array<{ retry_allowed_at: string; retry_allowed_by: string; invoice_status: "awaiting_payment" }> };
        confirm_verified_retreat_booking: { Args: { p_invoice_id: string }; Returns: Array<{ booking_id: string; booking_reference: string; booking_status: "confirmed"; invoice_status: "paid"; hold_status: HoldStatus; confirmed_at: string; confirmed_by: string }> };
        get_public_booking_by_slug: { Args: { p_public_slug: string }; Returns: Array<{ booking_reference: string; booking_status: "confirmed"; guest_name: string | null; retreat_type_name: string; retreat_format: RetreatFormat; guest_count: number; start_date: string; end_date: string | null; nights: number; created_at: string }> };
        get_public_booking_preparation: { Args: { p_booking_slug: string }; Returns: Array<{ preferred_contact_method: "whatsapp" | "phone" | "email"; contact_detail: string; participant_names: string | null; arrival_method: string | null; arrival_notes: string | null; dietary_requirements: string | null; accessibility_requirements: string | null; cally_notes: string | null }> };
        save_public_booking_preparation: { Args: { p_booking_slug: string; p_preferred_contact_method: "whatsapp" | "phone" | "email"; p_contact_detail: string; p_participant_names: string | null; p_arrival_method: string | null; p_arrival_notes: string | null; p_dietary_requirements: string | null; p_accessibility_requirements: string | null; p_cally_notes: string | null }; Returns: boolean };
        create_public_invoice: { Args: { p_public_quote_slug: string; p_amount_usd: number; p_eth_price_usd: number; p_amount_eth: number; p_wallet_address: string; p_invoice_reference: string; p_public_slug: string }; Returns: Array<{ public_slug: string }> };
        get_public_invoice_by_quote_slug: { Args: { p_public_quote_slug: string }; Returns: Array<{ public_slug: string }> };
        submit_quote_payment: { Args: { raw_token: string; p_tx_hash?: string | null }; Returns: boolean };
        verify_quote_payment: { Args: { p_quote_id: string; p_tx_hash?: string | null }; Returns: boolean };
      submit_retreat_enquiry: {
        Args: {
          p_full_name: string;
          p_email: string;
          p_phone: string;
          p_country: string;
          p_retreat_product_id: string;
          p_retreat_format: RetreatFormat;
          p_guest_count: number;
          p_selected_date: string | null;
          p_alternative_date: string | null;
          p_event_id: string | null;
          p_message: string | null;
          p_referral_code: string | null;
          p_referral_source: string | null;
        };
        Returns: string;
      };
      submit_retreat_enquiry_with_dates: { Args: { p_full_name:string; p_email:string; p_phone:string; p_country:string; p_retreat_product_id:string; p_retreat_format:RetreatFormat; p_guest_count:number; p_selected_date:string|null; p_selected_end_date:string|null; p_alternative_date:string|null; p_event_id:string|null; p_message:string|null; p_referral_code:string|null; p_referral_source:string|null }; Returns:string };
      submit_general_retreat_enquiry: { Args: { p_full_name:string; p_email:string; p_phone:string; p_country:string; p_message:string|null; p_referral_code:string|null; p_referral_source:string|null }; Returns:string };
      update_retreat_booking: {
        Args: { target_booking_id: string; target_booking_status: BookingStatus; target_payment_status: PaymentStatus };
        Returns: undefined;
      };
    };
    Enums: { teaser_status: TeaserStatus; teaser_visibility: TeaserVisibility; contribution_category: ContributionCategory; contribution_status: ContributionStatus; affiliate_commission_rule_type: AffiliateCommissionRuleType; affiliate_commission_status: "pending" | "available"; store_payment_status: StorePaymentStatus; affiliate_account_status: AffiliateAccountStatus; retreat_format: RetreatFormat; enquiry_status: EnquiryStatus; quote_status: QuoteStatus; payment_status: PaymentStatus; booking_status: BookingStatus; inner_sanctum_membership_status: InnerSanctumMembershipStatus; inner_sanctum_membership_type: InnerSanctumMembershipType; inner_sanctum_membership_source: InnerSanctumMembershipSource; store_product_type: StoreProductType; store_product_status: StoreProductStatus; store_fulfillment_type: StoreFulfillmentType; store_order_status: StoreOrderStatus; store_fulfillment_authorization_source: StoreFulfillmentAuthorizationSource; store_claim_status: StoreClaimStatus };
    CompositeTypes: Record<string, never>;
  };
  teaser_private: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: {
      valid_copy: { Args: { value: string; max_length: number }; Returns: boolean };
      valid_graffiti: { Args: { lines: string[] }; Returns: boolean };
      valid_image_path: { Args: { path: string; teaser_id: string; slot: number }; Returns: boolean };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
