"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth";

function refresh() { revalidatePath("/admin/referrals"); revalidatePath("/inner-sanctum/you"); }
export async function setReferralStatus(formData: FormData) { const id=z.uuid().parse(formData.get("referral_id")); const status=z.enum(["active","disabled"]).parse(formData.get("status")); const state=await requireAdmin(); if(!state) throw new Error("Not authorized"); const {error}=await state.supabase.from("inner_sanctum_referrals").update({status}).eq("id",id); if(error) throw new Error("Referral status could not be updated."); refresh(); }
export async function addFilthPoints(formData: FormData) { const userId=z.uuid().parse(formData.get("user_id")); const points=z.coerce.number().int().min(-10000).max(10000).refine((value)=>value!==0).parse(formData.get("points")); const reason=z.string().trim().min(3).max(500).parse(formData.get("reason")); const state=await requireAdmin(); if(!state) throw new Error("Not authorized"); const {error}=await state.supabase.rpc("admin_add_filth_points",{p_user_id:userId,p_points:points,p_reason:reason}); if(error) throw new Error("Filth could not be adjusted."); refresh(); }
export async function recordTestConversion(formData: FormData) { const orderId=z.uuid().parse(formData.get("order_id")); const userId=z.uuid().parse(formData.get("referred_user_id")); const state=await requireAdmin(); if(!state) throw new Error("Not authorized"); const {error}=await state.supabase.rpc("admin_record_test_referral_conversion",{p_order_id:orderId,p_referred_user_id:userId}); if(error) { console.error("Admin test referral conversion failed", { code: error.code, message: error.message, details: error.details, hint: error.hint, orderId, referredUserId: userId }); throw new Error("The test conversion could not be recorded."); } refresh(); }
