import { addFilthPoints, recordTestConversion, setReferralStatus } from "@/app/admin/referrals/actions";
import { SubmitButton } from "@/components/submit-button";
import { requireAdmin } from "@/lib/auth";

export default async function AdminReferralsPage() {
 const state=await requireAdmin(); if(!state) return null;
 const [{data:members},{data:referrals},{data:events},{data:levels},{data:earned},{data:milestones},{data:attributions},{data:orders},{data:conversions}] = await Promise.all([
  state.supabase.rpc("admin_list_inner_sanctum_members"),state.supabase.from("inner_sanctum_referrals").select("*").order("created_at"),state.supabase.from("inner_sanctum_filth_events").select("*"),state.supabase.from("inner_sanctum_filth_levels").select("*").eq("status","active").order("threshold"),state.supabase.from("inner_sanctum_member_filth_milestones").select("*"),state.supabase.from("inner_sanctum_filth_milestones").select("*"),state.supabase.from("store_order_referrals").select("*"),state.supabase.from("store_orders").select("id,order_reference,buyer_email,user_id"),state.supabase.from("inner_sanctum_referral_conversions").select("*")
 ]);
 const email=new Map((members??[]).map((m)=>[m.user_id,m.email??m.user_id])); const totals=new Map<string,number>(); for(const event of events??[]) totals.set(event.user_id,(totals.get(event.user_id)??0)+event.points); const conversionCounts=new Map<string,number>(); for(const conversion of conversions??[]) conversionCounts.set(conversion.referrer_user_id,(conversionCounts.get(conversion.referrer_user_id)??0)+1); const milestoneNames=new Map((milestones??[]).map((m)=>[m.id,m.title])); const earnedBy=new Map<string,string[]>(); for(const item of earned??[]) earnedBy.set(item.user_id,[...(earnedBy.get(item.user_id)??[]),milestoneNames.get(item.milestone_id)??"Milestone"]); const orderMap=new Map((orders??[]).map((o)=>[o.id,o]));
 return <><div className="admin-title"><div><p className="eyebrow">Inner Sanctum</p><h1>Referrals</h1></div></div><section className="admin-panel"><div className="table-wrap"><table><thead><tr><th>Member</th><th>Code</th><th>Status</th><th>Conversions</th><th>Filth</th><th>Level</th><th>Milestones</th><th>Action</th></tr></thead><tbody>{referrals?.map((referral)=>{const total=totals.get(referral.user_id)??0; const level=[...(levels??[])].reverse().find((item)=>item.threshold<=total); return <tr key={referral.id}><td>{email.get(referral.user_id)??referral.user_id}</td><td>{referral.code}</td><td>{referral.status}</td><td>{conversionCounts.get(referral.user_id)??0}</td><td>{total}</td><td>{level?.title??"Before Level 1"}</td><td>{(earnedBy.get(referral.user_id)??[]).join(", ")||"—"}</td><td><form action={setReferralStatus}><input type="hidden" name="referral_id" value={referral.id}/><input type="hidden" name="status" value={referral.status==="active"?"disabled":"active"}/><button className="button secondary small" type="submit">{referral.status==="active"?"Disable":"Enable"}</button></form></td></tr>})}</tbody></table></div></section><section className="admin-panel"><h2>Adjust Filth</h2><form action={addFilthPoints} className="form-grid"><label>Member<select name="user_id" required>{members?.map((m)=><option key={m.user_id} value={m.user_id}>{m.email??m.user_id}</option>)}</select></label><label>Points<input name="points" type="number" required/></label><label className="full-span">Reason<input name="reason" minLength={3} maxLength={500} required/></label><SubmitButton>Apply adjustment</SubmitButton></form></section><section className="admin-panel"><h2>Record test conversion</h2><p className="admin-caution">Testing only. This does not mark an order paid or represent payment verification.</p><form action={recordTestConversion} className="form-grid"><label>Attributed order<select name="order_id" required>{attributions?.filter((a)=>!a.conversion_id).map((a)=>{const order=orderMap.get(a.order_id); return <option key={a.id} value={a.order_id}>{order?.order_reference??a.order_id} · {order?.buyer_email}</option>})}</select></label><label>Referred member<select name="referred_user_id" required>{members?.map((m)=><option key={m.user_id} value={m.user_id}>{m.email??m.user_id}</option>)}</select></label><SubmitButton>Record test conversion</SubmitButton></form></section></>;
}
