import { createAvailability, toggleAvailability } from "@/app/actions/admin";
import { AvailabilityCalendar } from "@/components/availability-calendar";
import { SubmitButton } from "@/components/submit-button";
import { requireAdmin } from "@/lib/auth";
import { RETREAT_FORMATS, formatDate, formatLabels } from "@/lib/domain";
import { dateOnlyMonthGrid } from "@/lib/retreat-dates";
function currentMonth() { return new Date().toISOString().slice(0, 7); }
function validMonth(value: string | undefined) { return value && /^\d{4}-(0[1-9]|1[0-2])$/.test(value) ? value : currentMonth(); }
function monthGridBounds(month: string) { const days = dateOnlyMonthGrid(month); return { start: days[0], end: days.at(-1)! }; }
export default async function AvailabilityPage({ searchParams }: { searchParams: Promise<{ month?: string }> }) {
  const state = await requireAdmin(); if (!state) return null; const month = validMonth((await searchParams).month); const bounds = monthGridBounds(month);
  const [{ data: products }, { data: rows }, { data: events }, { data: bookings }, { data: holds }] = await Promise.all([
    state.supabase.from("retreat_products").select("id,name,allowed_formats").order("sort_order"),
    state.supabase.from("retreat_availability").select("id,retreat_product_id,retreat_format,start_date,end_date,state,capacity").lte("start_date", bounds.end).gte("end_date", bounds.start).order("start_date"),
    state.supabase.from("retreat_events").select("id,title,retreat_product_id,retreat_format,start_date,end_date,capacity,available_places,status,description").lte("start_date", bounds.end).gte("end_date", bounds.start).order("start_date"),
    state.supabase.from("retreat_bookings").select("id,enquiry_id,retreat_product_id,retreat_type_name,retreat_format,start_date,end_date,guest_count,retreat_event_id,booking_status,payment_status").is("retreat_event_id", null).in("booking_status", ["confirmed", "completed"]).lte("start_date", bounds.end).or(`end_date.gte.${bounds.start},and(end_date.is.null,start_date.gte.${bounds.start})`).order("start_date"),
    state.supabase.from("retreat_holds").select("id,quote_id,enquiry_id,retreat_product_id,retreat_format,start_date,end_date,guest_count,retreat_event_id,status,expires_at").lte("start_date", bounds.end).or(`end_date.gte.${bounds.start},and(end_date.is.null,start_date.gte.${bounds.start})`).order("start_date"),
  ]);
  const names = new Map(products?.map((product) => [product.id, product.name])); const calendarRows = (rows ?? []) as unknown as Parameters<typeof AvailabilityCalendar>[0]["availability"];
  return <><div className="admin-title"><div><p className="eyebrow">Inventory</p><h1>Availability</h1></div></div><AvailabilityCalendar month={month} products={products ?? []} availability={calendarRows} events={events ?? []} bookings={bookings ?? []} holds={(holds ?? []) as never} /><section className="admin-panel"><h2>Add date or range</h2><form action={createAvailability} className="form-grid compact-form"><label>Retreat<select name="product_id"><option value="">Any Retreat</option>{products?.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label>Format<select name="retreat_format"><option value="">Any Format</option>{RETREAT_FORMATS.map((format) => <option value={format} key={format}>{formatLabels[format]}</option>)}</select></label><label>Start date<input type="date" name="start_date" required /></label><label>End date<input type="date" name="end_date" required /></label><label>State<select name="state"><option value="available">Available</option><option value="blocked">Blocked</option></select></label><label>Capacity (optional)<input type="number" name="capacity" min="1" /></label><div className="full-span"><SubmitButton>Add availability</SubmitButton></div></form></section><div className="card-list">{rows?.map((row) => <article className="admin-card" key={row.id}><div><strong>{row.retreat_product_id ? names.get(row.retreat_product_id) : "Any Retreat"}</strong><p>{row.retreat_format ? formatLabels[row.retreat_format] : "Any Format"} · {formatDate(row.start_date)} – {formatDate(row.end_date)} · {row.capacity ? `Capacity ${row.capacity}` : "No capacity limit"} · {row.state === "available" ? "Available" : "Blocked"}</p></div><form action={toggleAvailability}><input type="hidden" name="id" value={row.id} /><input type="hidden" name="current" value={row.state} /><button className="button small secondary" type="submit">{row.state === "available" ? "Block" : "Make available"}</button></form></article>)}{!rows?.length && <p>No availability has been added.</p>}</div></>;
}
