create or replace function retreat_private.validate_private_booking(p_retreat_product_id uuid,p_retreat_format public.retreat_format,p_start_date date,p_end_date date,p_guest_count smallint,p_exclude_booking_id uuid default null) returns void language plpgsql security definer set search_path='' as $$
declare requested_end date;
begin
 if not (select retreat_private.is_retreat_admin()) then raise exception 'Not authorized'; end if;
 if p_start_date is null or p_guest_count not between 1 and 50 or p_retreat_format='join_a_group' then raise exception 'Invalid private booking details'; end if;
 requested_end:=coalesce(p_end_date,p_start_date); if requested_end<p_start_date then raise exception 'Private booking end date must be on or after the start date'; end if;
 if not exists(select 1 from public.retreat_products p where p.id=p_retreat_product_id and p.is_published and p_retreat_format=any(p.allowed_formats)) then raise exception 'The selected retreat is no longer available.'; end if;
 perform pg_catalog.pg_advisory_xact_lock(735391);
 if exists(select 1 from public.retreat_events e where e.status='published' and e.start_date<=requested_end and e.end_date>=p_start_date) then raise exception 'These dates are reserved for a published event.'; end if;
 if exists(select 1 from generate_series(p_start_date::timestamp,requested_end::timestamp,interval '1 day') d where not exists(select 1 from public.retreat_availability a where (a.retreat_product_id is null or a.retreat_product_id=p_retreat_product_id) and (a.retreat_format is null or a.retreat_format=p_retreat_format) and a.state='available' and a.start_date<=d::date and a.end_date>=d::date and (a.capacity is null or a.capacity>=p_guest_count)) or exists(select 1 from public.retreat_availability a where (a.retreat_product_id is null or a.retreat_product_id=p_retreat_product_id) and (a.retreat_format is null or a.retreat_format=p_retreat_format) and a.state='blocked' and a.start_date<=d::date and a.end_date>=d::date)) then raise exception 'The configured availability no longer permits these private retreat dates.'; end if;
 if exists(select 1 from public.retreat_bookings b where (p_exclude_booking_id is null or b.id<>p_exclude_booking_id) and b.retreat_event_id is null and b.booking_status in('confirmed','completed') and b.start_date<=requested_end and coalesce(b.end_date,b.start_date)>=p_start_date) then raise exception 'These dates are already occupied by another confirmed retreat.'; end if;
 if exists(select 1 from public.retreat_holds h where h.status='active' and h.expires_at>now() and h.retreat_event_id is null and h.start_date<=requested_end and coalesce(h.end_date,h.start_date)>=p_start_date) then raise exception 'These dates are already reserved by an active quote.'; end if;
end; $$;
revoke all on function retreat_private.validate_private_booking(uuid,public.retreat_format,date,date,smallint,uuid) from public,anon,authenticated;

create or replace function public.create_retreat_event(p_title text,p_product_id uuid,p_start_date date,p_end_date date,p_capacity smallint,p_status public.event_status,p_description text) returns uuid language plpgsql security definer set search_path='' as $$ declare eid uuid; begin if not (select retreat_private.is_retreat_admin()) then raise exception 'Not authorized'; end if; if p_capacity<=0 or p_end_date<p_start_date then raise exception 'Invalid event details'; end if; perform pg_catalog.pg_advisory_xact_lock(735391); if p_status='published' and exists(select 1 from public.retreat_events e where e.status='published' and e.start_date<=p_end_date and e.end_date>=p_start_date) then raise exception 'These dates overlap another published event.'; end if; if p_status='published' and exists(select 1 from public.retreat_bookings b where b.retreat_event_id is null and b.booking_status in('confirmed','completed') and b.start_date<=p_end_date and coalesce(b.end_date,b.start_date)>=p_start_date) then raise exception 'These dates are already occupied by a private retreat.'; end if; insert into public.retreat_events(title,retreat_product_id,retreat_format,start_date,end_date,capacity,available_places,status,description) values(p_title,p_product_id,'join_a_group',p_start_date,p_end_date,p_capacity,p_capacity,p_status,nullif(p_description,'')) returning id into eid; return eid; end; $$;
revoke all on function public.create_retreat_event(text,uuid,date,date,smallint,public.event_status,text) from public,anon;
grant execute on function public.create_retreat_event(text,uuid,date,date,smallint,public.event_status,text) to authenticated;

create or replace function public.update_retreat_event(p_event_id uuid,p_title text,p_start_date date,p_end_date date,p_capacity smallint,p_status public.event_status,p_description text) returns void language plpgsql security definer set search_path='' as $$ declare e public.retreat_events%rowtype; confirmed smallint; held smallint; begin if not (select retreat_private.is_retreat_admin()) then raise exception 'Not authorized'; end if; select * into e from public.retreat_events where id=p_event_id for update; if e.id is null then raise exception 'Event not found'; end if; select coalesce(sum(guest_count),0)::smallint into confirmed from public.retreat_bookings where retreat_event_id=e.id and booking_status in('confirmed','completed'); select coalesce(sum(guest_count),0)::smallint into held from public.retreat_holds where retreat_event_id=e.id and status='active' and expires_at>now(); if p_capacity<confirmed+held then raise exception 'Capacity cannot be lower than committed or held places'; end if; perform pg_catalog.pg_advisory_xact_lock(735391); if e.status='published' and (p_start_date<>e.start_date or p_end_date<>e.end_date) and (confirmed+held)>0 then raise exception 'Event dates cannot change while guest commitments exist'; end if; if e.status='published' and p_status='draft' and (confirmed+held)>0 then raise exception 'Committed events cannot be unpublished'; end if; if p_status='published' and exists(select 1 from public.retreat_events x where x.id<>e.id and x.status='published' and x.start_date<=p_end_date and x.end_date>=p_start_date) then raise exception 'These dates overlap another published event.'; end if; if p_status='published' and exists(select 1 from public.retreat_bookings b where b.retreat_event_id is null and b.booking_status in('confirmed','completed') and b.start_date<=p_end_date and coalesce(b.end_date,b.start_date)>=p_start_date) then raise exception 'These dates are already occupied by a private retreat.'; end if; update public.retreat_events set title=p_title,start_date=p_start_date,end_date=p_end_date,capacity=p_capacity,available_places=greatest(0,p_capacity-confirmed),status=p_status,description=nullif(p_description,'') where id=e.id; end; $$;
revoke all on function public.update_retreat_event(uuid,text,date,date,smallint,public.event_status,text) from public,anon;
grant execute on function public.update_retreat_event(uuid,text,date,date,smallint,public.event_status,text) to authenticated;
