import Link from "next/link";
import { createManualBooking, updateBooking } from "@/app/actions/admin";
import { RetreatDurationFields } from "@/components/retreat-duration-fields";
import { SubmitButton } from "@/components/submit-button";
import { requireAdmin } from "@/lib/auth";
import { BOOKING_STATUSES, formatDate, formatLabels, PAYMENT_STATUSES, RETREAT_FORMATS, titleCaseStatus } from "@/lib/domain";
export default async function BookingsPage({ searchParams }: { searchParams: Promise<{ start_date?: string }> }) {
  const state = await requireAdmin(); if (!state) return null; const query = await searchParams; const defaultStart = /^\d{4}-\d{2}-\d{2}$/.test(query.start_date ?? "") ? query.start_date : "";
  const [{ data: bookings }, { data: products }, { data: events }] = await Promise.all([state.supabase.from("retreat_bookings").select("*").order("created_at", { ascending: false }), state.supabase.from("retreat_products").select("id,name").order("sort_order"), state.supabase.from("retreat_events").select("id,title,retreat_product_id,start_date,end_date,capacity,available_places,status").order("start_date")]);
  return <><div className="admin-title"><div><p className="eyebrow">Confirmed and historical</p><h1>Bookings</h1></div></div><section className="admin-panel"><h2>Create manual booking</h2><form action={createManualBooking} className="form-grid compact-form"><label>Retreat<select name="product_id" required>{products?.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Format<select name="retreat_format" required>{RETREAT_FORMATS.map((f) => <option key={f} value={f}>{formatLabels[f]}</option>)}</select></label><RetreatDurationFields arrivalDefault={defaultStart} /><label>Guests<input type="number" name="guest_count" min="1" max="50" defaultValue="1" required /></label><label>Booking status<select name="booking_status" defaultValue="confirmed">{BOOKING_STATUSES.map((s) => <option key={s} value={s}>{titleCaseStatus(s)}</option>)}</select></label><label>Payment status<select name="payment_status" defaultValue="unpaid">{PAYMENT_STATUSES.map((s) => <option key={s} value={s}>{titleCaseStatus(s)}</option>)}</select></label><label>Group event (optional)<select name="event_id"><option value="">No group event</option>{events?.map((e) => <option key={e.id} value={e.id}>{e.title} · {formatDate(e.start_date)} – {formatDate(e.end_date)}</option>)}</select></label><div className="full-span"><SubmitButton>Create manual booking</SubmitButton></div></form></section><div className="table-wrap"><table><thead><tr><th>Reference</th><th>Source</th><th>Retreat</th><th>Format</th><th>Dates</th><th>Guests</th><th>Status</th><th>Payment</th><th>Update</th></tr></thead><tbody>{bookings?.map((b) => <tr key={b.id}><td>{b.enquiry_id ? <Link href={`/admin/enquiries/${b.enquiry_id}`}>{b.id.slice(0, 8).toUpperCase()}</Link> : b.id.slice(0, 8).toUpperCase()}</td><td>{titleCaseStatus(b.booking_source)}</td><td>{b.retreat_type_name}</td><td>{formatLabels[b.retreat_format]}</td><td>Arrival {formatDate(b.start_date)}{b.end_date ? ` · Checkout ${formatDate(new Date(`${b.end_date}T00:00:00Z`).toISOString().slice(0,10))}` : ""}</td><td>{b.guest_count}</td><td>{titleCaseStatus(b.booking_status)}</td><td>{titleCaseStatus(b.payment_status)}</td><td><form action={updateBooking}><input type="hidden" name="booking_id" value={b.id} /><select name="booking_status" defaultValue={b.booking_status}>{BOOKING_STATUSES.map((s) => <option key={s} value={s}>{titleCaseStatus(s)}</option>)}</select><select name="payment_status" defaultValue={b.payment_status}>{PAYMENT_STATUSES.map((s) => <option key={s} value={s}>{titleCaseStatus(s)}</option>)}</select><SubmitButton className="button small secondary">Save</SubmitButton></form></td></tr>)}</tbody></table></div></>;
}
